### ISSUE TITLE
Docker container client cannot connect with Server container

### ISSUE THREAD

**Issue by SalahAdDin** [Kozea/wdb#121]
I'm trying to use this tool for debugging my project.

I installed the client in the main container and i'm using two different images with the server inside.
Each time i try to debug my code i get this:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f72d88aeda0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2601, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4759, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/var/lib/odoo/addons/11.0/project/sale_order_project/models/project.py", line 13, in _compute_sale_orders_count
    wdb.set_trace()
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 994, in set_trace
    wdb = Wdb.get(server=server, port=port)
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 103, in get
    Wdb.__init__(wdb, server, port, force_uuid)
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 150, in __init__
    self.get_breakpoints()
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 243, in get_breakpoints
    breaks = loads(breaks)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

I am using `compose` for orquestation:
```yaml
    web:
        restart: always
        build: odoo
        image: odoo
        networks:
            - odoo-network
        container_name: odoo.web
        ports:
            - '8069:8069'
            - '8072:8072'
        environment:
            - PASSWORD
            - WDB_NO_BROWSER_AUTO_OPEN
            - WDB_SOCKET_SERVER
            - WERKZEUG_DEBUG_PIN
        depends_on:
            - db
            - debug
            - mailhog
        volumes:
            - 'odoo-web-data:/var/lib/odoo'
            - './addons:/var/lib/odoo/addons/11.0'
            - './odoo/odoo.conf:/etc/odoo/odoo.conf'
    db:
        restart: always
        image: postgres
        networks:
            - odoo-network
        container_name: odoo.db
        environment:
            - POSTGRES_DB
            - POSTGRES_PASSWORD
            - POSTGRES_USER
    debug:
        # image: yajo/wdb-server
        image: fabricadesoftwarelibre/libregob-depurador:18.1
        networks:
            - odoo-network
        container_name: odoo.debug
        ports:
            - "1984:1984"
```

Main server can connect with the database without any problem.

I'm using this image for server: https://hub.docker.com/r/yajo/wdb-server/
And i installed the cliente here:
```Dockerfile
FROM debian:stretch
...
RUN pip3 install --upgrade wheel
RUN pip3 install --upgrade bokeh \
        boto3 \
        email_validator \
        fdfgen \
        imageio \
        moviepy \
        num2words \
        numpy \
        phonenumbers \
        Pygments \
        psycopg2 \
        Wand \
        # watchdog \
        wdb \
        xlrd \
        xlsxwriter \
        xlwt
```

Why cannot the cliente connect with the server?

Thank you.

**Comment by damendieta** [comment]
Looks like it's a docker update, I had a completely working environment and when installed on Ubuntu 18.04 with latest docker and docker compose, it stopped working.
As the configuration was completely working, I can only assume that the problem is not the configuration, but the updates.

Thanks.

**Comment by SalahAdDin** [comment]
But also i think i didn't update `Docker`and `docker-compose` yet.

**Comment by damendieta** [comment]
With Docker 18.06-0-ce and Docker compose 1.22.0, it fails.

**Comment by SalahAdDin** [comment]
These are my notifications:
```bash
                  .o+`                 salahaddin@TulipanROG
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 4.17.12-arch1-1-ARCH
               `+oooooo:               Uptime: 1d 15h 58m
               -+oooooo+:              Packages: 1434
             `/:-:++oooo+:             Shell: zsh 5.5.1
            `/++++/+++++++:            Resolution: 1920x1080
           `/++++++++++++++:           DE: Deepin 15.7
          `/+++ooooooooooooo/`         WM: Deepin WM
         ./ooosssso++osssssso+`        WM Theme: Materia-light-compact
        .oossssso-````/ossssss+`       GTK Theme: Materia-light-compact [GTK2/3]
       -osssssso.      :ssssssso.      Icon Theme: Halo
      :osssssss/        osssso+++.     CPU: Intel Core i7-4720HQ @ 8x 3.6GHz [67.0°C]
     /ossssssss/        +ssssooo/-     GPU: GeForce GTX 960M
   `/ossssso+/:-        -:/+osssso+-   RAM: 11608MiB / 15932MiB

docker-compose -v                                                                                                                                                 ✔  5223  00:28:58 
docker-compose version 1.18.0, build 8dd22a9


docker -v                                                                                                                                                         ✔  5224  00:30:00 
Docker version 18.05.0-ce, build f150324782

```

And it is not working with this setup.

**Comment by SalahAdDin** [comment]
@oliviakozea it still does not work with the last image.

**Comment by SalahAdDin** [comment]
It is working right now, it seems we cannot pass the variable by `.env`, i put them directly and it is working.

Thanks.
