### ISSUE TITLE
Invalid syntax issue when trying to run wdb.server.py on linux python2.7

### ISSUE THREAD

**Issue by sujithkumar1993** [Kozea/wdb#124]
Traceback (most recent call last):
  File "/home/sujith/anaconda2/bin/wdb.server.py", line 6, in <module>
    from tornado.ioloop import IOLoop
  File "/home/sujith/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 52, in <module>
    from tornado.concurrent import Future, is_future, chain_future, future_set_exc_info, future_add_done_callback  # noqa: E501
  File "/home/sujith/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 48, in <module>
    import asyncio
  File "/home/sujith/anaconda2/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/home/sujith/anaconda2/lib/python2.7/site-packages/asyncio/selectors.py", line 69
    class BaseSelector(metaclass = ABCMeta):
                                 ^
SyntaxError: invalid syntax

**Comment by paradoxxxzero** [comment]
Something is wrong with your installation, you shouldn't have an asyncio package in your site-packages.
