### ISSUE TITLE
Unable to launch wdb server. 

### ISSUE THREAD

**Issue by amjith** [Kozea/wdb#41]
I just installed wdb and tried to launch, but faced with the following error message. I'm running OS X. I installed it via `pip install wdb.server`.

```
amjith@amjith-mbp: ~/Dropbox/code/python/pgcli master ⚡
$ wdb.server.py
Traceback (most recent call last):
  File "/usr/local/bin/wdb.server.py", line 2, in <module>
    from wdb_server import server
  File "/usr/local/lib/python2.7/site-packages/wdb_server/__init__.py", line 241, in <module>
    from wdb_server.utils import refresh_process, LibPythonWatcher
  File "/usr/local/lib/python2.7/site-packages/wdb_server/utils.py", line 23, in <module>
    import psutil
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 149, in <module>
    import psutil._psosx as _psplatform
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 168, in <module>
    pids = cext.pids
AttributeError: 'module' object has no attribute 'pids'
FAIL: 1

amjith@amjith-mbp: ~/Dropbox/code/python/pgcli master ⚡
$ pip freeze | grep wdb
wdb==2.0.7
wdb.server==2.0.7

amjith@amjith-mbp: ~/Dropbox/code/python/pgcli master ⚡
$ pip freeze | grep psutil
psutil==2.2.0
```

**Comment by paradoxxxzero** [comment]
As you noticed this is a bug between psutils and your mac, https://github.com/giampaolo/psutil/issues/577
So I'm gonna close this one.

**Comment by amjith** [comment]
You're right it was an issue with my installation of psutil and I just resolved it. 

Thank you for wdb.
