### ISSUE TITLE
.cerror: [Errno 4] Interrupted system call

### ISSUE THREAD

**Issue by cnv1989** [Kozea/wdb#43]
```
Traceback (most recent call last):
  File "/home/nchunduru/projects/HearsayLabs/.virtualenv/local/lib/python2.7/site-packages/wdb/ui.py", line 162, in loop
    stop = self.interact()
  File "/home/nchunduru/projects/HearsayLabs/.virtualenv/local/lib/python2.7/site-packages/wdb/ui.py", line 189, in interact
    message = self.db.receive()
  File "/home/nchunduru/projects/HearsayLabs/.virtualenv/local/lib/python2.7/site-packages/wdb/__init__.py", line 576, in receive
    data = self._socket.recv_bytes()
  File "/home/nchunduru/projects/HearsayLabs/.virtualenv/local/lib/python2.7/site-packages/wdb/_compat.py", line 135, in recv_bytes
    size, = struct.unpack("!i", self._handle.recv(4))
error: [Errno 4] Interrupted system call

```

**Comment by alex-bender** [comment]
I have the same.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 162, in loop
    stop = self.interact()
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 189, in interact
    message = self.db.receive()
  File "/usr/local/lib/python2.7/dist-packages/wdb/__init__.py", line 633, in receive
    data = self._socket.recv_bytes()
  File "/usr/local/lib/python2.7/dist-packages/wdb/_compat.py", line 142, in recv_bytes
    size, = struct.unpack("!i", self._handle.recv(4))
error: [Errno 4] Interrupted system call

```

**Comment by paradoxxxzero** [comment]
This should have been fixed in git. See duplicate #56
