### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by Yajo** [Kozea/wdb#57]
Writing in the interpreter any letter yields this.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wdb/ui.py", line 171, in loop
    stop = self.interact()
  File "/usr/lib/python2.7/site-packages/wdb/ui.py", line 208, in interact
    rv = fun(data)
  File "/usr/lib/python2.7/site-packages/wdb/ui.py", line 545, in do_complete
    completion = loads(data)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by rv-kip** [comment]
For me (#62) this was a versioning mismatch between client and server.

**Comment by Yajo** [comment]
Probably, I have not been able to reproduce after updating.
