### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by rv-kip** [Kozea/wdb#62]
Browser shows this error as soon as I type a character:
```
Client Server version mismatch !
Server is 2.1.1 and Client is 2.1.8
Error in Wdb, this is bad
ValueError: No JSON object could be decoded
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 171, in loop
    stop = self.interact()
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 208, in interact
    rv = fun(data)
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 545, in do_complete
    completion = loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by rv-kip** [comment]
Duh. Version mismatch was causing the problem. Updated `wdb` and `wdb.server` and that fixed the issue.
