### ISSUE TITLE
Postmortem Issue

### ISSUE THREAD

**Issue by blaggacao** [Kozea/wdb#80]
Hi, I get the following traceback:

```
2016-08-06 18:11:25,259 6 ERROR feat_test_sales_incl openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/src/odoo-cc/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/src/odoo-cc/openerp/http.py", line 286, in _handle_exception
    openerp.tools.config, sys.exc_info())
  File "/home/src/odoo-cc/openerp/tools/debugger.py", line 17, in post_mortem
    pdb.post_mortem(info[2])
  File "/usr/local/lib/python2.7/dist-packages/wdb/__init__.py", line 971, in post_mortem
    wdb.interaction(None, t)
  File "/usr/local/lib/python2.7/dist-packages/wdb/__init__.py", line 780, in interaction
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 88, in __init__
    self.stack, self.trace, self.index = self.db.get_trace(frame, tb)
  File "/usr/local/lib/python2.7/dist-packages/wdb/__init__.py", line 660, in get_trace
    if filename[0] == '<' and filename[-1] == '>':
IndexError: string index out of range
```

**Comment by blaggacao** [comment]
`info[1]` proves, this is an error which occurs in a user supplied, dynamically evaluated python code, which has an error.

------------

This case has not been taken into account while evaluating:
`if filename[0] == '<' and filename[-1] == '>'`

-------------

- The nicest thing would be to be able to debug user provided code, as well.
- The second nicest thing would be to handle this case gracefully.

**Comment by blaggacao** [comment]
@Yajo Have you had this casein your experience with wdb & odoo, as well?

**Comment by Yajo** [comment]
Not, sorry.

**Comment by paradoxxxzero** [comment]
This should fix it, but empty filename is not really encouraged in code objects. (When there's no file, set it to something like '<string>')

**Comment by blaggacao** [comment]
Nice, thanks a lot! Will test it with the next release and feed back, if need be or to confirm it's solved.

**Comment by paradoxxxzero** [comment]
I will release soon, when #81 is fixed
