### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 17: ordinal not in range(128)

### ISSUE THREAD

**Issue by blaggacao** [Kozea/wdb#83]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 180, in loop
    stop = self.interact()
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 219, in interact
    rv = fun(data)
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 435, in do_eval
    self.db.hooked = self.handle_exc()
  File "/usr/local/lib/python2.7/dist-packages/wdb/ui.py", line 817, in handle_exc
    escape(type_.__name__), escape(str(value)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 17: ordinal not in range(128)

```

**Comment by blaggacao** [comment]
Caused by this exception:
```
except Exception as e:
                logger.error(
                    "%s: error in migration script %s: %s" %
                    (module, filename, str(e).decode('utf8')))
                logger.exception(e)
                raise
```

**Comment by sametmax** [comment]
The logger should use %r instead of %s so that you get the repr of the objects which is garantied to be ascii.
