### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 17359: illegal multibyte sequence

### ISSUE THREAD

**Issue by viweei** [Kozea/wdb#93]
```shell
(.env) C:\Users\xxx\Workspace\mkdx>pip install wdb
Collecting wdb
  Downloading https://pypi.doubanio.com/packages/ec/49/8738da1b004a5b48102771f046ec87e7864cd803c382b3d8d2ec725335e5/wdb-3.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-build-xu771q7s\wdb\setup.py", line 14, in <module>
        __version__ = re.search("__version__ = '([^']+)'", fd.read()).group(1)
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 17359: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\viwee\AppData\Local\Temp\pip-build-xu771q7s\wdb\

```

**Comment by viweei** [comment]
solution
I find a long time did not find 0xa6 characters, I tried atom, vscode, sublime, vim ~ 
finally, I modified the setup.py file, look like....
```python
ROOT = os.path.dirname(__file__)
with open(os.path.join(ROOT, 'wdb', '__init__.py')) as fd:
    __version__ = re.search("__version__ = '([^']+)'", fd.read()).group(1)
```
change to 

```python
with open(os.path.join(ROOT, 'wdb', '__init__.py'), encoding='utf-8') as fd:
```

It can install....O_O!
