### ISSUE TITLE
tornado 4.5 is causing problems (raise RuntimeError("Method not supported for Web Sockets"))

### ISSUE THREAD

**Issue by krzysztof** [Kozea/wdb#97]
With a recent release of tornado 4.5 (I have tested this with tornado 4.5.0 and 4.5.1 on Python 3.5), wdb is failing to connect to the stream properly. The wdb page opens but it displays only that:
![wdb_error](https://cloud.githubusercontent.com/assets/656365/25276984/1915a9a8-269d-11e7-8435-a7a9045f3add.png)

Meanwhile the server throws the following exception (repeated 4 times):
```
[E 170421 14:12:53 iostream:565] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/home/krnowak/env/foo35/lib/python3.5/site-packages/tornado/iostream.py", line 562, in wrapper
        return callback(*args)
      File "/home/krnowak/env/foo35/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/krnowak/env/foo35/lib/python3.5/site-packages/wdb_server/streams.py", line 54, in read_frame
        websockets.send(uuid, frame)
      File "/home/krnowak/env/foo35/lib/python3.5/site-packages/wdb_server/state.py", line 38, in send
        self._send(sck, data)
      File "/home/krnowak/env/foo35/lib/python3.5/site-packages/wdb_server/state.py", line 114, in _send
        sck.write(data)
      File "/home/krnowak/env/foo35/lib/python3.5/site-packages/tornado/websocket.py", line 474, in _raise_not_supported_for_websockets
        raise RuntimeError("Method not supported for Web Sockets")
```

After downgrading to tornado==4.4, the problem does not occur.

**Comment by paradoxxxzero** [comment]
Thanks for the report, should be fixed in 3.1.5
